//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./cluster_types');
//HELPER FUNCTIONS AND STRUCTURES

ClusterService_registe_args = function(args) {
  this.id = null;
  this.request = null;
  if (args) {
    if (args.id !== undefined && args.id !== null) {
      this.id = args.id;
    }
    if (args.request !== undefined && args.request !== null) {
      this.request = args.request;
    }
  }
};
ClusterService_registe_args.prototype = {};
ClusterService_registe_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.id = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.request = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ClusterService_registe_args.prototype.write = function(output) {
  output.writeStructBegin('ClusterService_registe_args');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.STRING, 1);
    output.writeString(this.id);
    output.writeFieldEnd();
  }
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRING, 2);
    output.writeString(this.request);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ClusterService_registe_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
ClusterService_registe_result.prototype = {};
ClusterService_registe_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ClusterService_registe_result.prototype.write = function(output) {
  output.writeStructBegin('ClusterService_registe_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ClusterService_unregiste_args = function(args) {
  this.id = null;
  this.request = null;
  if (args) {
    if (args.id !== undefined && args.id !== null) {
      this.id = args.id;
    }
    if (args.request !== undefined && args.request !== null) {
      this.request = args.request;
    }
  }
};
ClusterService_unregiste_args.prototype = {};
ClusterService_unregiste_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.id = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.request = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ClusterService_unregiste_args.prototype.write = function(output) {
  output.writeStructBegin('ClusterService_unregiste_args');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.STRING, 1);
    output.writeString(this.id);
    output.writeFieldEnd();
  }
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRING, 2);
    output.writeString(this.request);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ClusterService_unregiste_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
ClusterService_unregiste_result.prototype = {};
ClusterService_unregiste_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ClusterService_unregiste_result.prototype.write = function(output) {
  output.writeStructBegin('ClusterService_unregiste_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ClusterService_process_args = function(args) {
  this.fromid = null;
  this.toid = null;
  this.request = null;
  if (args) {
    if (args.fromid !== undefined && args.fromid !== null) {
      this.fromid = args.fromid;
    }
    if (args.toid !== undefined && args.toid !== null) {
      this.toid = args.toid;
    }
    if (args.request !== undefined && args.request !== null) {
      this.request = args.request;
    }
  }
};
ClusterService_process_args.prototype = {};
ClusterService_process_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.fromid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.toid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.request = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ClusterService_process_args.prototype.write = function(output) {
  output.writeStructBegin('ClusterService_process_args');
  if (this.fromid !== null && this.fromid !== undefined) {
    output.writeFieldBegin('fromid', Thrift.Type.STRING, 1);
    output.writeString(this.fromid);
    output.writeFieldEnd();
  }
  if (this.toid !== null && this.toid !== undefined) {
    output.writeFieldBegin('toid', Thrift.Type.STRING, 2);
    output.writeString(this.toid);
    output.writeFieldEnd();
  }
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRING, 3);
    output.writeString(this.request);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ClusterService_process_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
ClusterService_process_result.prototype = {};
ClusterService_process_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ClusterService_process_result.prototype.write = function(output) {
  output.writeStructBegin('ClusterService_process_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ClusterService_invoke_args = function(args) {
  this.toid = null;
  this.request = null;
  if (args) {
    if (args.toid !== undefined && args.toid !== null) {
      this.toid = args.toid;
    }
    if (args.request !== undefined && args.request !== null) {
      this.request = args.request;
    }
  }
};
ClusterService_invoke_args.prototype = {};
ClusterService_invoke_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.toid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.request = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ClusterService_invoke_args.prototype.write = function(output) {
  output.writeStructBegin('ClusterService_invoke_args');
  if (this.toid !== null && this.toid !== undefined) {
    output.writeFieldBegin('toid', Thrift.Type.STRING, 1);
    output.writeString(this.toid);
    output.writeFieldEnd();
  }
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRING, 2);
    output.writeString(this.request);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ClusterService_invoke_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
ClusterService_invoke_result.prototype = {};
ClusterService_invoke_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ClusterService_invoke_result.prototype.write = function(output) {
  output.writeStructBegin('ClusterService_invoke_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ClusterServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
ClusterServiceClient.prototype = {};
ClusterServiceClient.prototype.seqid = function() { return this._seqid; }
ClusterServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
ClusterServiceClient.prototype.registe = function(id, request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_registe(id, request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_registe(id, request);
  }
};

ClusterServiceClient.prototype.send_registe = function(id, request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('registe', Thrift.MessageType.CALL, this.seqid());
  var args = new ClusterService_registe_args();
  args.id = id;
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ClusterServiceClient.prototype.recv_registe = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ClusterService_registe_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('registe failed: unknown result');
};
ClusterServiceClient.prototype.unregiste = function(id, request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_unregiste(id, request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_unregiste(id, request);
  }
};

ClusterServiceClient.prototype.send_unregiste = function(id, request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('unregiste', Thrift.MessageType.CALL, this.seqid());
  var args = new ClusterService_unregiste_args();
  args.id = id;
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ClusterServiceClient.prototype.recv_unregiste = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ClusterService_unregiste_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('unregiste failed: unknown result');
};
ClusterServiceClient.prototype.process = function(fromid, toid, request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_process(fromid, toid, request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_process(fromid, toid, request);
  }
};

ClusterServiceClient.prototype.send_process = function(fromid, toid, request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('process', Thrift.MessageType.CALL, this.seqid());
  var args = new ClusterService_process_args();
  args.fromid = fromid;
  args.toid = toid;
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ClusterServiceClient.prototype.recv_process = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ClusterService_process_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('process failed: unknown result');
};
ClusterServiceClient.prototype.invoke = function(toid, request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_invoke(toid, request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_invoke(toid, request);
  }
};

ClusterServiceClient.prototype.send_invoke = function(toid, request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('invoke', Thrift.MessageType.CALL, this.seqid());
  var args = new ClusterService_invoke_args();
  args.toid = toid;
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ClusterServiceClient.prototype.recv_invoke = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ClusterService_invoke_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('invoke failed: unknown result');
};
ClusterServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
ClusterServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

ClusterServiceProcessor.prototype.process_registe = function(seqid, input, output) {
  var args = new ClusterService_registe_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.registe.length === 2) {
    Q.fcall(this._handler.registe, args.id, args.request)
      .then(function(result) {
        var result = new ClusterService_registe_result({success: result});
        output.writeMessageBegin("registe", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("registe", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.registe(args.id, args.request, function (err, result) {
      if (err == null) {
        var result = new ClusterService_registe_result((err != null ? err : {success: result}));
        output.writeMessageBegin("registe", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("registe", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

ClusterServiceProcessor.prototype.process_unregiste = function(seqid, input, output) {
  var args = new ClusterService_unregiste_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.unregiste.length === 2) {
    Q.fcall(this._handler.unregiste, args.id, args.request)
      .then(function(result) {
        var result = new ClusterService_unregiste_result({success: result});
        output.writeMessageBegin("unregiste", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("unregiste", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.unregiste(args.id, args.request, function (err, result) {
      if (err == null) {
        var result = new ClusterService_unregiste_result((err != null ? err : {success: result}));
        output.writeMessageBegin("unregiste", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("unregiste", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

ClusterServiceProcessor.prototype.process_process = function(seqid, input, output) {
  var args = new ClusterService_process_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.process.length === 3) {
    Q.fcall(this._handler.process, args.fromid, args.toid, args.request)
      .then(function(result) {
        var result = new ClusterService_process_result({success: result});
        output.writeMessageBegin("process", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("process", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.process(args.fromid, args.toid, args.request, function (err, result) {
      if (err == null) {
        var result = new ClusterService_process_result((err != null ? err : {success: result}));
        output.writeMessageBegin("process", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("process", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

ClusterServiceProcessor.prototype.process_invoke = function(seqid, input, output) {
  var args = new ClusterService_invoke_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.invoke.length === 2) {
    Q.fcall(this._handler.invoke, args.toid, args.request)
      .then(function(result) {
        var result = new ClusterService_invoke_result({success: result});
        output.writeMessageBegin("invoke", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("invoke", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.invoke(args.toid, args.request, function (err, result) {
      if (err == null) {
        var result = new ClusterService_invoke_result((err != null ? err : {success: result}));
        output.writeMessageBegin("invoke", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("invoke", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

