//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./master_types');
//HELPER FUNCTIONS AND STRUCTURES

MasterService_invoke_args = function(args) {
  this.method = null;
  this.request = null;
  if (args) {
    if (args.method !== undefined && args.method !== null) {
      this.method = args.method;
    }
    if (args.request !== undefined && args.request !== null) {
      this.request = args.request;
    }
  }
};
MasterService_invoke_args.prototype = {};
MasterService_invoke_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.method = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.request = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MasterService_invoke_args.prototype.write = function(output) {
  output.writeStructBegin('MasterService_invoke_args');
  if (this.method !== null && this.method !== undefined) {
    output.writeFieldBegin('method', Thrift.Type.STRING, 1);
    output.writeString(this.method);
    output.writeFieldEnd();
  }
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRING, 2);
    output.writeString(this.request);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MasterService_invoke_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
MasterService_invoke_result.prototype = {};
MasterService_invoke_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MasterService_invoke_result.prototype.write = function(output) {
  output.writeStructBegin('MasterService_invoke_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MasterService_registe_args = function(args) {
  this.type = null;
  this.serviceId = null;
  this.request = null;
  if (args) {
    if (args.type !== undefined && args.type !== null) {
      this.type = args.type;
    }
    if (args.serviceId !== undefined && args.serviceId !== null) {
      this.serviceId = args.serviceId;
    }
    if (args.request !== undefined && args.request !== null) {
      this.request = args.request;
    }
  }
};
MasterService_registe_args.prototype = {};
MasterService_registe_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.type = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.serviceId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.request = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MasterService_registe_args.prototype.write = function(output) {
  output.writeStructBegin('MasterService_registe_args');
  if (this.type !== null && this.type !== undefined) {
    output.writeFieldBegin('type', Thrift.Type.STRING, 1);
    output.writeString(this.type);
    output.writeFieldEnd();
  }
  if (this.serviceId !== null && this.serviceId !== undefined) {
    output.writeFieldBegin('serviceId', Thrift.Type.STRING, 2);
    output.writeString(this.serviceId);
    output.writeFieldEnd();
  }
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRING, 3);
    output.writeString(this.request);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MasterService_registe_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
MasterService_registe_result.prototype = {};
MasterService_registe_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MasterService_registe_result.prototype.write = function(output) {
  output.writeStructBegin('MasterService_registe_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MasterService_workerList_args = function(args) {
};
MasterService_workerList_args.prototype = {};
MasterService_workerList_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MasterService_workerList_args.prototype.write = function(output) {
  output.writeStructBegin('MasterService_workerList_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MasterService_workerList_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
MasterService_workerList_result.prototype = {};
MasterService_workerList_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MasterService_workerList_result.prototype.write = function(output) {
  output.writeStructBegin('MasterService_workerList_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MasterService_readme_args = function(args) {
  this.serviceId = null;
  if (args) {
    if (args.serviceId !== undefined && args.serviceId !== null) {
      this.serviceId = args.serviceId;
    }
  }
};
MasterService_readme_args.prototype = {};
MasterService_readme_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.serviceId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MasterService_readme_args.prototype.write = function(output) {
  output.writeStructBegin('MasterService_readme_args');
  if (this.serviceId !== null && this.serviceId !== undefined) {
    output.writeFieldBegin('serviceId', Thrift.Type.STRING, 1);
    output.writeString(this.serviceId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MasterService_readme_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
MasterService_readme_result.prototype = {};
MasterService_readme_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MasterService_readme_result.prototype.write = function(output) {
  output.writeStructBegin('MasterService_readme_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MasterService_ask_args = function(args) {
  this.method = null;
  if (args) {
    if (args.method !== undefined && args.method !== null) {
      this.method = args.method;
    }
  }
};
MasterService_ask_args.prototype = {};
MasterService_ask_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.method = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MasterService_ask_args.prototype.write = function(output) {
  output.writeStructBegin('MasterService_ask_args');
  if (this.method !== null && this.method !== undefined) {
    output.writeFieldBegin('method', Thrift.Type.STRING, 1);
    output.writeString(this.method);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MasterService_ask_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
MasterService_ask_result.prototype = {};
MasterService_ask_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MasterService_ask_result.prototype.write = function(output) {
  output.writeStructBegin('MasterService_ask_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MasterServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
MasterServiceClient.prototype = {};
MasterServiceClient.prototype.seqid = function() { return this._seqid; }
MasterServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
MasterServiceClient.prototype.invoke = function(method, request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_invoke(method, request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_invoke(method, request);
  }
};

MasterServiceClient.prototype.send_invoke = function(method, request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('invoke', Thrift.MessageType.CALL, this.seqid());
  var args = new MasterService_invoke_args();
  args.method = method;
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

MasterServiceClient.prototype.recv_invoke = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new MasterService_invoke_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('invoke failed: unknown result');
};
MasterServiceClient.prototype.registe = function(type, serviceId, request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_registe(type, serviceId, request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_registe(type, serviceId, request);
  }
};

MasterServiceClient.prototype.send_registe = function(type, serviceId, request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('registe', Thrift.MessageType.CALL, this.seqid());
  var args = new MasterService_registe_args();
  args.type = type;
  args.serviceId = serviceId;
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

MasterServiceClient.prototype.recv_registe = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new MasterService_registe_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('registe failed: unknown result');
};
MasterServiceClient.prototype.workerList = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_workerList();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_workerList();
  }
};

MasterServiceClient.prototype.send_workerList = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('workerList', Thrift.MessageType.CALL, this.seqid());
  var args = new MasterService_workerList_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

MasterServiceClient.prototype.recv_workerList = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new MasterService_workerList_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('workerList failed: unknown result');
};
MasterServiceClient.prototype.readme = function(serviceId, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_readme(serviceId);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_readme(serviceId);
  }
};

MasterServiceClient.prototype.send_readme = function(serviceId) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('readme', Thrift.MessageType.CALL, this.seqid());
  var args = new MasterService_readme_args();
  args.serviceId = serviceId;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

MasterServiceClient.prototype.recv_readme = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new MasterService_readme_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('readme failed: unknown result');
};
MasterServiceClient.prototype.ask = function(method, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_ask(method);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_ask(method);
  }
};

MasterServiceClient.prototype.send_ask = function(method) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ask', Thrift.MessageType.CALL, this.seqid());
  var args = new MasterService_ask_args();
  args.method = method;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

MasterServiceClient.prototype.recv_ask = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new MasterService_ask_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('ask failed: unknown result');
};
MasterServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
MasterServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

MasterServiceProcessor.prototype.process_invoke = function(seqid, input, output) {
  var args = new MasterService_invoke_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.invoke.length === 2) {
    Q.fcall(this._handler.invoke, args.method, args.request)
      .then(function(result) {
        var result = new MasterService_invoke_result({success: result});
        output.writeMessageBegin("invoke", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("invoke", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.invoke(args.method, args.request, function (err, result) {
      if (err == null) {
        var result = new MasterService_invoke_result((err != null ? err : {success: result}));
        output.writeMessageBegin("invoke", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("invoke", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

MasterServiceProcessor.prototype.process_registe = function(seqid, input, output) {
  var args = new MasterService_registe_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.registe.length === 3) {
    Q.fcall(this._handler.registe, args.type, args.serviceId, args.request)
      .then(function(result) {
        var result = new MasterService_registe_result({success: result});
        output.writeMessageBegin("registe", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("registe", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.registe(args.type, args.serviceId, args.request, function (err, result) {
      if (err == null) {
        var result = new MasterService_registe_result((err != null ? err : {success: result}));
        output.writeMessageBegin("registe", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("registe", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

MasterServiceProcessor.prototype.process_workerList = function(seqid, input, output) {
  var args = new MasterService_workerList_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.workerList.length === 0) {
    Q.fcall(this._handler.workerList)
      .then(function(result) {
        var result = new MasterService_workerList_result({success: result});
        output.writeMessageBegin("workerList", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("workerList", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.workerList(function (err, result) {
      if (err == null) {
        var result = new MasterService_workerList_result((err != null ? err : {success: result}));
        output.writeMessageBegin("workerList", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("workerList", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

MasterServiceProcessor.prototype.process_readme = function(seqid, input, output) {
  var args = new MasterService_readme_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.readme.length === 1) {
    Q.fcall(this._handler.readme, args.serviceId)
      .then(function(result) {
        var result = new MasterService_readme_result({success: result});
        output.writeMessageBegin("readme", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("readme", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.readme(args.serviceId, function (err, result) {
      if (err == null) {
        var result = new MasterService_readme_result((err != null ? err : {success: result}));
        output.writeMessageBegin("readme", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("readme", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

MasterServiceProcessor.prototype.process_ask = function(seqid, input, output) {
  var args = new MasterService_ask_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.ask.length === 1) {
    Q.fcall(this._handler.ask, args.method)
      .then(function(result) {
        var result = new MasterService_ask_result({success: result});
        output.writeMessageBegin("ask", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("ask", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.ask(args.method, function (err, result) {
      if (err == null) {
        var result = new MasterService_ask_result((err != null ? err : {success: result}));
        output.writeMessageBegin("ask", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("ask", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

